/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cliente;

/**
 *
 * @author Hiury
 */
public class TelaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
        cadCliente.setText("<html> Cadastrar <br> Cliente </html>");
        daCliente.setText("<html> Dados <br> Cliente </html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        daCliente = new javax.swing.JButton();
        cadCliente = new javax.swing.JButton();
        tela2 = new javax.swing.JDesktopPane();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daCliente.setBackground(new java.awt.Color(0, 102, 204));
        daCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        daCliente.setForeground(new java.awt.Color(255, 255, 255));
        daCliente.setText("Comprar");
        daCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daClienteActionPerformed(evt);
            }
        });
        getContentPane().add(daCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 0, 374, 125));

        cadCliente.setBackground(new java.awt.Color(0, 102, 204));
        cadCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cadCliente.setForeground(new java.awt.Color(255, 255, 255));
        cadCliente.setText("Comprar");
        cadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadClienteActionPerformed(evt);
            }
        });
        getContentPane().add(cadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 373, 125));

        javax.swing.GroupLayout tela2Layout = new javax.swing.GroupLayout(tela2);
        tela2.setLayout(tela2Layout);
        tela2Layout.setHorizontalGroup(
            tela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        tela2Layout.setVerticalGroup(
            tela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        getContentPane().add(tela2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 747, 582));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daClienteActionPerformed
        DadCliente venda = new DadCliente();
        tela2.add(venda);
        venda.setVisible(true);
    }//GEN-LAST:event_daClienteActionPerformed

    private void cadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadClienteActionPerformed
        CadCliente venda = new CadCliente();
        tela2.add(venda);
        venda.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cadClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadCliente;
    private javax.swing.JButton daCliente;
    private javax.swing.JDesktopPane tela2;
    // End of variables declaration//GEN-END:variables
}
