/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estoque;

import br.com.fornecedor.*;
import java.sql.*;
import br.com.dal_connexao.ModuloConexao;
import br.com.produto.Produtos;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hiury
 */
public class TelaEsotoquenew extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs2 = null;
    ResultSet rs = null;
    ResultSet rs3 = null;
    Statement st2;
    Statement st3;
    Statement st;
    public String nomes;
    Validacao altera = new Validacao();
    public int id;

    /**
     * Creates new form Fornecedores
     */
    public TelaEsotoquenew(int i1) {
        int i;
        id = i1;

        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        cadP = new javax.swing.JButton();
        cad = new javax.swing.JButton();
        fornecedorD = new javax.swing.JButton();
        telaF = new javax.swing.JDesktopPane();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadP.setBackground(new java.awt.Color(0, 102, 204));
        cadP.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cadP.setForeground(new java.awt.Color(255, 255, 255));
        cadP.setText("Estoque");
        cadP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPActionPerformed(evt);
            }
        });
        getContentPane().add(cadP, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 0, 248, 125));

        cad.setBackground(new java.awt.Color(0, 102, 204));
        cad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cad.setForeground(new java.awt.Color(255, 255, 255));
        cad.setText("Produto");
        cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadActionPerformed(evt);
            }
        });
        getContentPane().add(cad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 248, 125));

        fornecedorD.setBackground(new java.awt.Color(0, 102, 204));
        fornecedorD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fornecedorD.setForeground(new java.awt.Color(255, 255, 255));
        fornecedorD.setText("Relatório");
        fornecedorD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorDActionPerformed(evt);
            }
        });
        getContentPane().add(fornecedorD, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 0, 248, 125));

        javax.swing.GroupLayout telaFLayout = new javax.swing.GroupLayout(telaF);
        telaF.setLayout(telaFLayout);
        telaFLayout.setHorizontalGroup(
            telaFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        telaFLayout.setVerticalGroup(
            telaFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(telaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 745, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPActionPerformed
        Estoque cad = new Estoque();
        telaF.add(cad);
        cad.setVisible(true);

    }//GEN-LAST:event_cadPActionPerformed

    private void cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadActionPerformed
        Produtos cad = new Produtos(id);
        telaF.add(cad);
        cad.setVisible(true);
    }//GEN-LAST:event_cadActionPerformed

    private void fornecedorDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorDActionPerformed
     
    }//GEN-LAST:event_fornecedorDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cad;
    private javax.swing.JButton cadP;
    private javax.swing.JButton fornecedorD;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDesktopPane telaF;
    // End of variables declaration//GEN-END:variables
}
