/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.entregador;



/**
 *
 * @author ricar
 */
public class EntregadorTela extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuFinal
     */
    public EntregadorTela() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JDesktopPane();
        DadosEntregador = new javax.swing.JButton();
        cadEntregador = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        getContentPane().add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 745, 583));

        DadosEntregador.setBackground(new java.awt.Color(0, 102, 204));
        DadosEntregador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        DadosEntregador.setForeground(new java.awt.Color(255, 255, 255));
        DadosEntregador.setText("Dados Entregador");
        DadosEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DadosEntregadorActionPerformed(evt);
            }
        });
        getContentPane().add(DadosEntregador, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 0, 374, 125));

        cadEntregador.setBackground(new java.awt.Color(0, 102, 204));
        cadEntregador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cadEntregador.setForeground(new java.awt.Color(255, 255, 255));
        cadEntregador.setText("Cadastrar Entregador");
        cadEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadEntregadorActionPerformed(evt);
            }
        });
        getContentPane().add(cadEntregador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 373, 125));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DadosEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DadosEntregadorActionPerformed
       DadosEntregador mostraLista = new DadosEntregador();
       Panel1.add(mostraLista);
       mostraLista.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_DadosEntregadorActionPerformed

    private void cadEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadEntregadorActionPerformed
        CadastroEntregadores cadastrarPlanilha = new CadastroEntregadores();
        Panel1.add(cadastrarPlanilha);
        cadastrarPlanilha.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_cadEntregadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DadosEntregador;
    private javax.swing.JDesktopPane Panel1;
    private javax.swing.JButton cadEntregador;
    // End of variables declaration//GEN-END:variables
}
